spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mesin_db
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8010
  servlet:
    context-path: /
